language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
    - '7.2'
    - '7.3'
    - '7.4'

install:
    - composer install --dev

script:
   - ./vendor/bin/phpspec run --format=dot --no-code-generation